{% set data = load_setup_py_data() %}

package:
  name: flyemflows 
  version: {{ data['version'] }}

source:
  path: ../

build:
  noarch: python  
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - launchflow = flyemflows.bin.launchflow:main
    

requirements:
  build:
    - python >=3.6
    - python {{PY_VER}}*
    - setuptools
  run:
    - python >=3.6
    - python {{PY_VER}}*
    - requests
    - psutil

    - numpy
    - pandas
    - numba
    - scipy
    - scikit-image

    - dask
    - dask-jobqueue

    # Misc. serialization tools
    - lz4
    - cloudpickle
    - tblib

    - confiddler

    # DVID support
    - libdvid-cpp >=0.2
    - neuclease >=0.2.post107
    - dvidutils >=0.0.post44
    - dvid-resource-manager

    # misc. image formats
    - pillow
    - z5py
    
    # Needed for brainmaps support:
    - httplib2
    - oauth2client
    - snappy

test:
  requires:
    - pytest
    - numpy-allocation-tracking
    - dvid

  imports:
    - flyemflows

about:
  home: http://github.com/janelia-flyem/flyemflows
  license: BSD (3-clause)
  license_file: LICENSE.txt
  summary: Various compute-cluster workflows for the FlyEM project.
