# LOGGING
# https://docs.python.org/3.7/library/logging.config.html#logging-config-dictschema
logging:
  version: 1

  formatters:
    time_level:
      format: '[%(asctime)s] %(levelname)s %(message)s'

  handlers:
    standard:
      level: INFO
      formatter: time_level
      class: logging.StreamHandler
      stream: ext://sys.stdout

    errors:
      level: ERROR
      formatter: time_level
      class: logging.StreamHandler
      stream: ext://sys.stderr

  disable_existing_loggers: false

  root:
    level: INFO
    handlers: [standard, errors]

  loggers:
    distributed:
      level: INFO
    distributed.client:
      level: WARNING
    bokeh:
      level: CRITICAL
    tornado:
      level: CRITICAL
    tornado.application:
      level: ERROR
